The following error is known to occur with Linux kernel versions less than 2.6.24:
  select.error: (4, 'Interrupted system call')

This error has been observed after a SIGSTOP, followed by SIGCONT.
Treat it similar to EAGAIN if timeout is None, otherwise just return
without any events.

Thanks to Jeremy Olexa <darkside@g.o> for reporting and testing this
patch.