In preprocess_ebuild_env(), move a filter_readonly_variables call out of a subshell since FreeBSD and prefix users have reported apparent corruption of the PATH environment variable that triggers calls to the wrong version of sed (one that does not support the -r option). An example of what users have observed:
>>> Source compiled.
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
Traceback (most recent call last):
  File "/usr/lib/portage/bin/filter-bash-environment.py", line 51, in <module>
    compile_egrep_pattern(args[0]), file_in, file_out)
  File "/usr/lib/portage/bin/filter-bash-environment.py", line 34, in filter_bash_environment
    file_out.write(line)
IOError: [Errno 32] Broken pipe